# -*- coding: utf-8 -*-
"""Agglomerative_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iiy2qPg6CHvGWd490mG7bKJimYb-K2jU
"""

from itertools import cycle
from scipy.cluster.hierarchy import dendrogram
from sklearn.cluster import AgglomerativeClustering
import numpy as np
from numpy import random
import matplotlib.pyplot as plt


# функция для отображения дендограммы (взято из депозитория sklearn)
def plot_dendrogram(model, **kwargs):

    # Children of hierarchical clustering
    children = model.children_

    # Distances between each pair of children
    # Since we don't have this information, we can use a uniform one for plotting
    distance = np.arange(children.shape[0])

    # The number of observations contained in each cluster level
    no_of_observations = np.arange(2, children.shape[0]+2)

    # Create linkage matrix and then plot the dendrogram
    linkage_matrix = np.column_stack([children, distance, no_of_observations]).astype(float)

    # Plot the corresponding dendrogram
    dendrogram(linkage_matrix, **kwargs)


# входные образы для кластеризации
# x = [(89, 151), (114, 120), (156, 110), (163, 153), (148, 215), (170, 229), (319, 166), (290, 178), (282, 222)]
P = [(random.randn()/6, random.randn()/6) for i in range(150)]
P.extend([(random.randn()/4 + 2.5, random.randn()/5) for i in range(150)])
P.extend([(random.randn()/5 + 1, random.randn()/2 + 1) for i in range(150)])
P.extend([(i/25 - 1, + random.randn()/20 - 1) for i in range(100)])
P.extend([(i/25 - 2.5, 3 - (i/50 - 2)**2 + random.randn()/20) for i in range(150)])
x = np.array(P)

NC = 5      # максимальное число кластеров (итоговых)

# агломеративная иерархическая кластеризация
clustering = AgglomerativeClustering(n_clusters=NC, linkage="ward") # количество кластеров и тип соединений между таксонами
x_pr = clustering.fit_predict(x)

# отображение результата кластеризации и дендограммы
f, ax = plt.subplots(1, 2)
for c, n in zip(cycle('bgrcmykgrcmykgrcmykgrcmykgrcmykgrcmyk'), range(NC)): # цикл цветов
    clst = x[x_pr == n].T                           # те элементы, что входят в кластер n
    ax[0].scatter(clst[0], clst[1], s=2, color=c)  # отображение точек (x, y, ширина, цвет)

plot_dendrogram(clustering, ax=ax[1])
plt.show()